/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oic_videoeditor_MainActivity */

#ifndef _Included_com_oic_videoeditor_MainActivity
#define _Included_com_oic_videoeditor_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oic_videoeditor_MainActivity
 * Method:    naMain
 * Signature: (Lcom/oic/videoeditor/MainActivity;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_oic_videoeditor_MainActivity_naMain
  (JNIEnv *, jclass, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
