/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oic_videoeditor_MainActivity_VideoFrameAdapter */

#ifndef _Included_com_oic_videoeditor_MainActivity_VideoFrameAdapter
#define _Included_com_oic_videoeditor_MainActivity_VideoFrameAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
