/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oic_videoeditor_MainActivity_DumpFrameTask */

#ifndef _Included_com_oic_videoeditor_MainActivity_DumpFrameTask
#define _Included_com_oic_videoeditor_MainActivity_DumpFrameTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
